version: '3.7'

services:
  # builds semantic and watches for changes
  bootstrap:
    image: mkieblesz/bootstrap
    ports:
      - '9001:9001'
    volumes:
      # bind docs server to 0.0.0.0 in order to make it availabe on host machine and use new base sass file
      - './bootstrap/package.json:/frontend/bootstrap/package.json'
      - './src:/frontend/src'
    command: npm start
    # command: npm run watch-css-main
